#main configuration
#to make a connection between database and pipeline

default_environment: default
environments:
  default:
    connections:
      duckdb:
        name: "duckdb-default"
        path: "isey.db"
